### ISSUE TITLE
Basic Ship Parts

### ISSUE THREAD

**Issue by kruemelkeksfan** [praetorianer777/dergeraet#3]
- [x] Floor 1x1
- [x] Wall 1x1
- [x] Window 1x1
- [x] Control Station
- [x] Reactor
- [x] Engine

**Comment by Alfadas** [comment]
l           w             h
- [ ] Floor 0,25m * 0,25m * 0,25m 
- [ ] Floor 0,5m * 0,5m * 0,25m
- [ ] Floor 1m * 1m * 0,25m 
- [ ] Floor 1m* 0,25m * 0,25m
- [ ] Wall 0,25m* 0,25m  * 0,25m 
- [ ] Wall 0,5m* 0,25m  * 0,5m 
- [ ] Wall 1m * 0,25m * 1m 
- [ ] Window 0,25m * 0,25m * 0,25m 
- [ ] Window 0,5m * 0,5m * 0,25m
- [ ] Window 0,25m* 0,25m  * 0,25m 
- [ ] Window 0,5m* 0,25m  * 0,5m
